In [1]:
import numpy as np

## Data Types & Attributes

In [3]:
# NumPy's main datatype is ndarray

a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
np.shape(a3)

(2, 3, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
# ndim => number of dimension

a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [15]:
# Create DataFrame from NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating Arrays

In [16]:
sample_array = np.array([1, 2, 3])

sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int64')

In [18]:
sample_array.size

3

In [19]:
sample_array.shape

(3,)

In [20]:
ones = np.ones((2, 3))

In [21]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
ones_two = np.ones((2, 4, 3))

In [23]:
ones_two

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [24]:
type(ones)

numpy.ndarray

In [25]:
ones.dtype

dtype('float64')

In [26]:
zeros = np.zeros((2, 3))

In [27]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
type(zeros)

numpy.ndarray

In [29]:
zeros.size

6

In [30]:
zeros.shape

(2, 3)

In [32]:
range_array = np.arange(2, 12, 2)

In [33]:
range_array

array([ 2,  4,  6,  8, 10])

In [34]:
range_array.size

5

In [35]:
type(range_array)

numpy.ndarray

In [36]:
random_array = np.random.randint(0, 10, size=(3, 5))

In [37]:
random_array

array([[8, 2, 9, 7, 2],
       [1, 7, 9, 7, 7],
       [0, 8, 8, 6, 7]])

In [38]:
random_array.size

15

In [39]:
random_array.shape

(3, 5)

In [40]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.30694325, 0.23071185, 0.12604975],
       [0.45193034, 0.14974562, 0.5838413 ],
       [0.22509365, 0.70166172, 0.04249123],
       [0.03606628, 0.65903946, 0.72294999],
       [0.07413345, 0.57903912, 0.15546835]])

In [42]:
random_array_3 = np.random.rand(2, 3)

random_array_3

array([[0.55340306, 0.02174768, 0.72649022],
       [0.96673093, 0.08378549, 0.1921569 ]])

In [43]:
random_array_a = np.random.randn(1, 4)
random_array_a

array([[-0.18563507,  0.15462411, -0.29607461, -0.02931159]])