# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [7]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [8]:
# Create a 1-dimensional NumPy array using np.array()
one_dim = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
two_dim = np.array([[1, 2, 3],
                    [4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()
three_dim = np.array([[[1, 2, 3], 
                       [4, 5, 6],
                       [7, 8, 9]],
                      [[10, 11, 12],
                       [13, 14, 15],
                       [16, 17, 18]]])

two_dim.ndim,three_dim.ndim, three_dim.shape

(2, 3, (2, 3, 3))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [9]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
one_dim.shape, one_dim.ndim, one_dim.dtype, one_dim.size, type(one_dim)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [10]:
# Attributes of 2-dimensional array

two_dim.shape, two_dim.ndim, two_dim.dtype, two_dim.size, type(two_dim)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [11]:
# Attributes of 3-dimensional array

three_dim.shape, three_dim.ndim, three_dim.dtype, three_dim.size, type(three_dim)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [12]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created

import pandas as pd

df = pd.DataFrame(two_dim)
df

0  1  2
0  1  2  3
1  4  5  6

In [13]:
# Create an array of shape (10, 2) with only ones

ones = np.ones([10, 2])
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
# Create an array of shape (7, 2, 3) of only zeros

ones_2 = np.ones((7, 2, 3))
ones_2

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [15]:
# Create an array within a range of 0 and 100 with step 3

array = np.arange(0, 100, 3)
array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [16]:
# Create a random array with numbers between 0 and 10 of size (7, 2)

array_2 = np.random.randint(0, 10, size=(7, 2))
array_2

array([[8, 4],
       [2, 1],
       [3, 6],
       [5, 6],
       [3, 4],
       [6, 3],
       [0, 2]])

In [17]:
# Create a random array of floats between 0 & 1 of shape (3, 5)

array_3 = np.random.randint(0, 1, size=(3, 5))
array_3

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [18]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
array_4 = np.random.randint(0, 10, size=(4, 6))
array_4

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [19]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
np.random.seed(0)
array_5 = np.random.randint(1, 10, size=(3, 7))

# Find the unique numbers in the array you just created

np.unique(array_5)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
array_5

array([[6, 1, 4, 4, 8, 4, 6],
       [3, 5, 8, 7, 9, 9, 2],
       [7, 8, 8, 9, 2, 6, 9]])

In [21]:
# Find the 0'th index of the latest array you created
array_5[0]

array([6, 1, 4, 4, 8, 4, 6])

In [22]:
# Get the first 2 rows of latest array you created

array_5[:2]

array([[6, 1, 4, 4, 8, 4, 6],
       [3, 5, 8, 7, 9, 9, 2]])

In [23]:
# Get the first 2 values of the first 2 rows of the latest array

array_5[:2, :2]

array([[6, 1],
       [3, 5]])

In [24]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

array_6 = np.random.randint(0, 10, size=(3,5))
array_7 = np.ones(shape=(3, 5))

In [25]:
# Add the two arrays together

array_8 = array_6 + array_7
array_8

array([[10.,  5.,  4.,  1.,  4.],
       [ 6.,  1.,  3.,  4.,  9.],
       [ 2.,  4.,  4.,  4.,  8.]])

In [26]:
# Create another array of ones of shape (5, 3)

array_9 = np.ones(shape=(5, 3))

In [27]:
# Try add the array of ones and the other most recent array together

array_a = array_8 + array_9.T
array_a

array([[11.,  6.,  5.,  2.,  5.],
       [ 7.,  2.,  4.,  5., 10.],
       [ 3.,  5.,  5.,  5.,  9.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [28]:
# Create another array of ones of shape (3, 5)

array_10 = np.ones(shape=(3, 5))

In [29]:
# Subtract the new array of ones from the other most recent array

array_b = array_a - array_10

In [30]:
# Multiply the ones array with the latest array

array_11 = array_10 * array_b
array_11

array([[10.,  5.,  4.,  1.,  4.],
       [ 6.,  1.,  3.,  4.,  9.],
       [ 2.,  4.,  4.,  4.,  8.]])

In [31]:
# Take the latest array to the power of 2 using '**'

array_11 ** 2

array([[100.,  25.,  16.,   1.,  16.],
       [ 36.,   1.,   9.,  16.,  81.],
       [  4.,  16.,  16.,  16.,  64.]])

In [32]:
# Do the same thing with np.square()

np.square(array_11)

array([[100.,  25.,  16.,   1.,  16.],
       [ 36.,   1.,   9.,  16.,  81.],
       [  4.,  16.,  16.,  16.,  64.]])

In [33]:
# Find the mean of the latest array using np.mean()

np.mean(array_11)

4.6

In [34]:
# Find the maximum of the latest array using np.max()
np.max(array_11)

10.0

In [35]:
# Find the minimum of the latest array using np.min()
np.min(array_11)

1.0

In [36]:
# Find the standard deviation of the latest array

array_11.std()

2.5768197453450252

In [37]:
# Find the variance of the latest array

array_11.var()

6.640000000000001

In [38]:
# Reshape the latest array to (3, 5, 1)
array_11.reshape(3, 5, 1)

array([[[10.],
        [ 5.],
        [ 4.],
        [ 1.],
        [ 4.]],

       [[ 6.],
        [ 1.],
        [ 3.],
        [ 4.],
        [ 9.]],

       [[ 2.],
        [ 4.],
        [ 4.],
        [ 4.],
        [ 8.]]])

In [39]:
# Transpose the latest array

array_11.T

array([[10.,  6.,  2.],
       [ 5.,  1.,  4.],
       [ 4.,  3.,  4.],
       [ 1.,  4.,  4.],
       [ 4.,  9.,  8.]])

What does the transpose do?

In [40]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)

array_12 = np.random.randint(0, 10, size=(3, 3))
array_13 = np.random.randint(0, 10, size=(3, 2))

array_12, array_13

(array([[0, 1, 9],
        [9, 0, 4],
        [7, 3, 2]]),
 array([[7, 2],
        [0, 0],
        [4, 5]]))

In [41]:
# Perform a dot product on the two newest arrays you created

array_12.dot(array_13)

array([[36, 45],
       [79, 38],
       [57, 24]])

In [42]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)

array_14 = np.random.randint(0, 10, size=(4, 3))
array_15 = np.random.randint(0, 10, size=(4, 3))

In [43]:
# Perform a dot product on the two newest arrays you created

array_14.dot(array_15.T)

array([[111,  47, 117,  92],
       [ 63,  30,  53,  44],
       [111,  79,  76,  74],
       [ 84,  21, 119,  86]])

It doesn't work. How would you fix it?

In [44]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both



Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [45]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables

array_16 = np.random.randint(0, 10, size=(3, 5))
array_17 = np.random.randint(0, 10, size=(3, 5))

In [46]:
# Compare the two arrays with '>'

array_16 > array_17

array([[ True,  True, False,  True,  True],
       [ True, False,  True,  True,  True],
       [ True, False, False, False, False]])

What happens when you compare the arrays with `>`?

In [47]:
# Compare the two arrays with '>='

array_16 >= array_17

array([[ True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True]])

In [48]:
# Find which elements of the first array are greater than 7

array_16 > 7

array([[False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False,  True]])

In [49]:
# Which parts of each array are equal? (try using '==')

array_16 == array_17

array([[False, False, False, False, False],
       [False,  True, False, False, False],
       [False,  True, False,  True,  True]])

In [50]:
# Sort one of the arrays you just created in ascending order

np.sort(array_17)

array([[0, 0, 1, 3, 5],
       [0, 2, 2, 3, 4],
       [0, 2, 5, 7, 9]])

In [51]:
# Sort the indexes of one of the arrays you just created

array_17.argsort()

array([[1, 3, 4, 0, 2],
       [3, 0, 2, 4, 1],
       [1, 0, 3, 2, 4]])

In [52]:
# Find the index with the maximum value in one of the arrays you've created

np.argmax(array_17)

14

In [53]:
# Find the index with the minimum value in one of the arrays you've created

np.argmin(array_17)

1

In [54]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created

np.argmax(array_17, axis=1)

array([2, 1, 4])

In [55]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created

np.argmin(array_17, axis=0)

array([1, 0, 1, 0, 0])

In [56]:
# Create an array of normally distributed random numbers

np.random.randn(3, 5)

array([[-0.04411241, -0.36326702, -0.01234481,  0.04212149,  1.95929589],
       [-0.1984257 ,  0.33053441, -1.43582841,  0.02752832,  1.12060466],
       [-0.22403878, -0.42018339,  0.99982969,  0.43103415, -0.65091287]])

In [57]:
# Create an array with 10 evenly spaced numbers between 1 and 100

np.arange(1, 100, 10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.